# Generated by Django 4.0 on 2022-01-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programminglanguages',
            options={'ordering': ['-title'], 'verbose_name': 'Знание', 'verbose_name_plural': 'Знания'},
        ),
        migrations.RemoveField(
            model_name='programminglanguages',
            name='id',
        ),
        migrations.AddField(
            model_name='programminglanguages',
            name='process',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Процесс'),
        ),
        migrations.AlterField(
            model_name='programminglanguages',
            name='title',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Язык'),
        ),
    ]
